data.df <- read.csv(paste("Training_1.csv"),sep = ",")
attach(data.df)
cor.test(data.df$Settle,data.df$P)
cor.test(data.df$Settle,data.df$Ngeo)
cor.test(Settle,D1)
plot(Settle,P,type = "l")
View(data.df)
model1<- read.csv(paste("Model1.csv"))
plot(model1$P,model1$Settle,main = "Pressure-Settlement graph",xlab = "Pressure(in KPa)",ylab = "Settlement(in mm)")
abline(lm(Settle~P,data = model1),col="red")
par(mfrow=c(1,1))
